version: '3'

services:
  trip-db:
    image: postgres:latest
    container_name: trip-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${DB_USER_ID}"
      POSTGRES_PASSWORD: "${DB_USER_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - trip-db:/var/lib/postgres
      - ./postgres-init.d:/docker-entrypoint-initdb.d/
    env_file:
      - .env

  trip-redis:
    image: redis:latest
    command: redis-server --port 6379
    container_name: trip-redis
    ports:
      - "6479:6379"
    volumes:
      - trip-redis:/val/lib/redis

  trip-backend:
    environment:
      SPRING_PROFILES_ACTIVE: dev
    build: .
    container_name: trip-backend
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - trip-db

volumes:
  trip-db:
  trip-redis:
