version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER_ID}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
    volumes:
      - ./db:/var/lib/postgres/data
      - ./postgres-init.d:/docker-entrypoint-initdb.d/
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    command: redis-server --port 6379
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/val/lib/redis

  backend:
    environment:
      SPRING_PROFILES_ACTIVE: dev
    build: ./travity-api
    container_name: backend
    expose:
      - 8080
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs  # 로그 파일을 저장할 볼륨 추가
    depends_on:
      db:
        condition: service_healthy

volumes:
  db:
  redis:
  backend:
